longview:
  apiKey: ENC[AES256_GCM,data:Atu281/raXieNCXwYUM3VaXCIaHjlVgeTpaGGz5GxCiMnGA=,iv:p5Byg82Rt+13Kl/8Cf8nKyL1+7fdsCqt+C4GXCgbiVc=,tag:nbStk6w6O3aNv1ufQlhHaA==,type:str]
sops:
  age:
    - recipient: age1qashjzd7sgl8fpat65v8qtjf96mlue8gp6fpr0w0wh9yukuj65eqthfmtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TktKUkpEU25XUWJLbWln
        WlhiYVlIeDl2Y1JYV01OMGRNa0x1WTd5eEZRClBBbzcrTTdmNEZDaVp1bGV5OFUv
        ZjRmRllldnZXUS9kSGVNOCtjYWplK3cKLS0tIGEzQ0VESVlPQm5ITHB6RG0zVjc3
        am5NUUVOaGh1SnErM2VQVEFzNXBFbkEK7IfV05QyHpzg5Db4/aPKiVvepUTo2+l5
        TI4LpN8HHuOG/gLITiMHozKzXzlvQr2cMGu5lSeGRgMHwoXzwIe7hA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ryaef6l2py87c79xhtlxdx7te4jglz4rsv298a9uwf9jze3ceprsnzuq8u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvc1N4clNoeDdJcmJNK0hh
        aGtTMFIyVHE4T2pGV0VrQkdDRm90MmQ5VGxJCnhwNElHY1NSTGQyMVBYYmJ2amRR
        WERyWlRnelJER2E3alBENWRQcGUrcmsKLS0tIDRPMHRsdXhpTFl6OHhDQ2lDY3pz
        YnlGYUFyaDJVdVpFSGllbVdmcEsybjAKrHtYLtBx+zsAjwOi+NC/bZcv3pUF80HS
        nwdTLDdiGRGaD5ZZkasKfqkZfRphW44m5f+PSJVVoSb1NY+6Ele+gQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T04:25:14Z"
  mac: ENC[AES256_GCM,data:+hoAfsAsTqk1aAhA2aeIvSQruMKN9Z3SndkRr0/M1k150kWCjxfg6GMYnHk8iDSQPILN8Ilu1xQB7gjIwlbcC2tjHcAwgqx2fFZ5A+otguatpK4XV7g3OJRQG2cwat1eDjMxVfPYvVWO0vXYluHjtpsNyjflDlmBLDrcGmHblfs=,iv:Gi5s3W3Ir53MkeQ7BojkSKq/uZeI5yb/akAJONS5Dug=,tag:3LpuDQ9kCm6yaBOGprP7JA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.7.3
