longview:
  apiKey: ENC[AES256_GCM,data:WxdVJ7vzLYm7e2skTePHBcudSY4BsxpAlzOWBd1teUbJBZY=,iv:p5Byg82Rt+13Kl/8Cf8nKyL1+7fdsCqt+C4GXCgbiVc=,tag:0WTvpz+NBj6xKKWW/3m6mw==,type:str]
sops:
  age:
    - recipient: age1qashjzd7sgl8fpat65v8qtjf96mlue8gp6fpr0w0wh9yukuj65eqthfmtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsT3d1bTU3MmZCTnZyY3JQ
        TXhVUU9NRHBJLzEyOFJydm15cU5DZW12SWhJCm9xc1JnOXNrY3pabFRZdC9aWEg2
        RVptbmR1U1VnSFNadDlDYVE1QUt1ZUUKLS0tIFpmVk5qS0hFRkhnL0t0SXZRUU91
        SmhTa1k4VVR6NVVINnpjOW9ubllpTUkKYt7W57qlsnjeVpLDmy9pK544L9tMeZD0
        L6TGdkKkc9z6XpNY85PY9h0VyT7OmBE3IPsoCR4nBvtwrtUV/gkT8Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ryaef6l2py87c79xhtlxdx7te4jglz4rsv298a9uwf9jze3ceprsnzuq8u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL1R0ZXVXQXpOZGFiZ01U
        T1Z0RVB3cUg0a2lFVDQyeEJsT1lzNitXSFhNClp1QWZEb2NnN3Zyc3I2dDdkZzN1
        UHhEcUlHeU1iY2tUekNOSEV5K2NzWmsKLS0tIEcrL3ExNVJpZ1g3elFYV2VOMlI2
        dUZQNlNRcEFPM21Fai90bVNTbk82RU0KMUkx8aho55l6NsltwDhJmTvMiqOJ9y6U
        tiiaET1iG9EV00inkHtGyGUZVOHQCf1/jhp54xcCXqsenHI+yVyXWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-25T23:31:23Z"
  mac: ENC[AES256_GCM,data:SX84HKz1AZByC0EoeBRFN5CQSy368bvp8t1TxW2HUVcbWpdorow3+JsHLgSr3d9TRfkZTvMgxS04QSfT1/4t2ISO+VhWWBrVIpcgy9zkz1FrM+wJzVO6Gwv/Ig2Ck8Pka34UcWo58hdgDo8i9tiMHbQ5POSyUL8cl6aWRiMiBhE=,iv:riyC3dK7xXcGmbDqHdhv5HZxOhafdeYpeFDt+8WyApQ=,tag:q+F644CZM2WsSIPaAz7UBQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.7.3
