longview:
  apiKey: ENC[AES256_GCM,data:sOXXW1Jn4lc9POBPUJNy4wWqItnelfxYeS2uMae+7G15IVA=,iv:p5Byg82Rt+13Kl/8Cf8nKyL1+7fdsCqt+C4GXCgbiVc=,tag:Z0GjdoK/A/oAJdiBEylm/g==,type:str]
sops:
  age:
    - recipient: age1qashjzd7sgl8fpat65v8qtjf96mlue8gp6fpr0w0wh9yukuj65eqthfmtd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWGNxSjF0N0V4MmtJdVgr
        ZVhFNnd5Z0xnOHZxMTlrT2R2MUpGT2NIWEg0CnIyNWFWRUtWaVozd3pBcndjWXpv
        cjhUdDZDMTF2MWRXbllWSHE3c0ZOcWsKLS0tIFZIbGhISWdScU1id0xsTllEcC9l
        L1Juc05mQk96S0lVcnZ6OEpvNGdTTnMKr9pP1Sqfb/pq5NvVWeNOKu/xUr6s4AmR
        0wq2R6RVp7fLA3YQT9j/dvObOPicY+e0oiFiQad2QS+9TaLpsM5R0g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ryaef6l2py87c79xhtlxdx7te4jglz4rsv298a9uwf9jze3ceprsnzuq8u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNTRjSmlWQnBvYllwSVlv
        WC9yS2YxZERHSlhKTEx4UGNGanJtajRLWlRZCnBlMzJlSXdjWi9sU2JGaGY1R3lV
        azlneE9XUFFYSFJIbzJsQmZnMTZBSTQKLS0tIExtd0U4bWNMT1NWWlIxYXp3NjFZ
        UnlJTEs0WUlyZ2FDZyswY3FaQ0Z2VTgKbAh+i54bHGKb9d3dY0arAHVhHn9HTqom
        9ilTUc1Dz12mgNESNSNAm0HIaKIbr6xkOV83iJGRbcGBcII69j2/Rw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age12hca0w6x72uljalz7kjhe4tphklywzzmq5vjcpldws3vyandsp5qpd9zm0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMDRRS3ZZVERlV0NlZzhQ
        NnJ0QVB2bk1sMDhTVjA2Tzg5Zk05SmlwRXg0ClAvMWUwU01IWHZSSUhzT3hHa3oy
        N1hEd1pRK3NwNEZTMVA4QlZaNjJ1UU0KLS0tIFUwbFhRR0N3cFhSSXZSckhUN2hU
        UVJ3UjduZmx1M0hIYnRka1o5czQ2alEK2PbwMutNASrCkiFZx7XQOMRmxyKxpjoD
        lJHhxL+5DsMiVe3dstUYD+wSMWksJ2utA0Nq7jvbur4hgSsu69z7ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-23T00:36:49Z"
  mac: ENC[AES256_GCM,data:X7acxImnQzEP30FUMhIe5o2HLHNzoyHcLAmeDUmBm65q3M0+70h4dh4MhIBBtsUsNE51eIJPIhDk8x4STsVm3a1uEdVLUWnYQNXbUmbboGA571VibHrTF2FnZ7YeAPY4b3Ev40lCJ5tvTBGxeB4tdvF1OxxU+DgkanvYV1mvDLo=,iv:Z0f8KUTQWbm0wU0denXM30EyiX4Iz/beA4LQp2ghhfs=,tag:OzTYelKudMxzYcx8QZb3jQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.7.3
