name: Update Flake
on:
  schedule:
    - cron: "0 0 * * 0" # Weekly Update
  workflow_dispatch:
permissions:
  pull-requests: write
  actions: write
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: nix flake update --commit-lock-file
      - run: nix shell nixpkgs#python3 nixpkgs#npins --command ./update-script.sh # Update pins & MC Mods
      - name: Check for changes in minecraft mods
        run: |
          if git diff --exit-code modules/nixos/minecraft-server/sources.json; then
            echo "Minecraft mods not updated"
          elif [ -s modules/nixos/minecraft-server/sources.json ]; then
            git add modules/nixos/minecraft-server/sources.json
            git commit -m "Update Minecraft mods"
          else
            echo "Minecraft mod update failed, skipping"
          fi
      - name: Check for changes in pins
        run: |
          if git diff --exit-code npins/sources.json; then
            echo "No pins updated, skipping"
          else
            git add npins
            git commit -m "Update pins"
          fi
      - name: Check for changes in wivrn APK
        run: |
          if git diff --exit-code modules/nixos/vr/wivrn-apk.json; then
            echo "WivrnAPK not updated"
          elif [ -s modules/nixos/vr/wivrn-apk.json ] && [ $(nix run nixpkgs#jaq -- -r .hash < 'modules/nixos/vr/wivrn-apk.json') != "" ]; then
            git add modules/nixos/vr/wivrn-apk.json
            git commit -m "Update WivrnAPK"
          else
            echo "Wivrn apk update failed, skipping"
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: "Auto update packages"
